### ISSUE TITLE
Explain project on README 

### ISSUE THREAD

**Issue by afx-nicolas** [afx-nicolas/blog-coderockr#1]
#### Description

Describe the project in the README, including information about main features, third-party dependencies, and screenshots of the app, and explain how to build and run the application.

#### Tasks

- [x] Add main features
- [x] Add dependencies list
- [x] Add screenshots
- [x] Add build and run instructions
