### ISSUE TITLE
Add single post page

### ISSUE THREAD

**Issue by afx-nicolas** [afx-nicolas/blog-coderockr#5]
#### Description

Add a dynamic post page based on the article id.

#### Tasks

- [x] Render a article post component
- [x] Show the main info about article
- [x] Render article rich-text
